-- Active: 1763615452463@@@443@EE@BALOU
SELECT *  FROM MED_CONSULTATION WHERE IDMEDECIN = 'DR00001' ORDER BY DATY DESC;
SELECT cl.NOM
FROM MED_ORDONNANCE mo 
JOIN CLIENT cl ON mo.OBSERVATION_SOINS = cl.ID
WHERE mo.ID_CONSULTATION = 'CONS000402';

SELECT * FROM MED_ORDONNANCE ORDER BY ID DESC

SELECT GETSEQVENTEDETAILS() AS ID FROM dual